export const BACKUP_TABELAS = [
  "configuracoes",
  "filiais",
  "planos",
  "associados",
  "dependentes",
  "mensalidades",
  "cobradores",
  "recebimentos_pendentes",
  "contas_financeiras",
  "caixa_sessoes",
  "caixa_movimentos",
  "servicos_funerarios",
  "servicos_produtos",
  "servico_checklist",
  "servico_financeiro",
  "servico_timeline",
  "estoque_itens",
  "estoque_movimentos",
  "crm_leads",
  "crm_stages",
  "vendas_pins",
  "profiles",
  "user_roles",
  "role_permissions",
  "user_permissions",
  "logs_auditoria",
] as const;

export type BackupTabela = (typeof BACKUP_TABELAS)[number];
